name: Sync Fork with Upstream

on:
  schedule:
    - cron: "0 0 * * *" # هر روز ساعت 00:00 UTC
  workflow_dispatch: # اجرای دستی از تب Actions

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/itsramin/blogon.git
          git fetch upstream

      - name: Merge upstream/master into fork's master
        run: |
          git checkout master
          git merge upstream/master --allow-unrelated-histories || true
          git push origin master
